INCDIR += ./uvm/uvm_express ./uvm/uvm_express ./uvm/uvm_express ./uvm/uvm_express

TESTSUITES = ./.__uvm_uvm_express_testsuite.sv
UNITTESTS = apb_coverage_agent_unit_test.sv apb_mon_unit_test.sv apb_if_unit_test.sv apb_coverage_unit_test.sv 

-include svunit.mk
include $(SVUNIT_INSTALL)/bin/cfg.mk
