//////////////////////////////////////////////////////
// This file was automatically generated by the Mltypemap utility
// Mltypemap version 14.10.045-b(32 bits)
// Generated on Sun Jun  1 14:30:19 2014
//////////////////////////////////////////////////////
`ifndef OPERATION_SVH
`define OPERATION_SVH
`include "uvm_macros.svh"


package xor1;
import uvm_pkg::*;
//------------------------------------------------------------
//Source: Specman
//Source type: xor1::operation
//Source Location: /home/yuvalg/testcase/xor_uvm_ml/operation.e:4

class operation extends uvm_object;

  // default ctor
  function new(string name = "operation");
    super.new(name);
  endfunction : new

  // First input
  rand bit a;
  // Second input
  rand bit b;
  int result_from_dut;
  `uvm_object_utils_begin(operation)
    `uvm_field_int(a, UVM_ALL_ON|UVM_DEC|UVM_UNSIGNED)
    `uvm_field_int(b, UVM_ALL_ON|UVM_DEC|UVM_UNSIGNED)
    `uvm_field_int(result_from_dut, UVM_ALL_ON|UVM_DEC)
  `uvm_object_utils_end
endclass : operation


endpackage : xor1
`endif 


