CHILD_UNITTESTS += ./modules/apb_slave/apb_slave_unit_test.sv

INCDIR += ./modules/apb_slave

CHILD_TESTSUITES = ./modules/apb_slave/.__modules_apb_slave_testsuite.sv



-include svunit.mk
include $(SVUNIT_INSTALL)/bin/cfg.mk
